- name: Create docker mysql directory
  file:
    path: "{{ user_home }}/docker/docker_mysql"
    owner: "{{ user_name }}"
    group: docker
    mode: 0550
    state: directory

- name: Copy Dockerfile
  copy:
    src: ./Dockerfile
    dest: "{{ user_home }}/docker/docker_mysql/Dockerfile"
    owner: "{{ user_name }}"
    group: docker
    mode: 0550
